language: cpp
compiler:
  - gcc
  - clang

before_install:
    - sudo apt-add-repository ppa:smspillaz/cmake-2.8.12 -y
    - sudo apt-get update -qq
    # Decrypting TOKEN_SHA
    - openssl aes-256-cbc -K $encrypted_f4b786671656_key -iv $encrypted_f4b786671656_iv -in auth-token.enc -out auth-token -d
env:
    global:
        - DOCKER_USERNAME=
        - DOCKER_PASSWORD=

install:
    - sudo apt-get install -qq texlive
    - sudo apt-get install -qq texlive-extra-utils
    - sudo apt-get install -q -y texlive-latex-extra
    - sudo apt-get install -qq libxml2-utils
    - sudo apt-get install -qq cmake cmake-data

script:
    - mkdir build
    - cd build
    - cmake -G "Unix Makefiles" -Dbuild_doc=ON -Dbuild_wizard=ON ..
    - make
    - make tests
    - make docs

deploy:
    # Deploys to Doxyparse official GitHub
    provider: script
    script: sh create-gh-release.sh
    on:
        branch: master

    # Deploys to DoxyParse official dockerhub
    provider: script
    script: sh deploy-2-dockerhub.sh
    on:
        branch: master
